
  name: 'CI'
  on:
    pull_request:
      branches:
        - main
      workflow_dispatch:

    # Allows you to run this workflow manually from the Actions tab
  # workflow_dispatch:

  # A workflow run is made up of one or more jobs that can run sequentially or in parallel
  jobs:
    # This workflow contains a single job called "build"
    build:
      # The type of runner that the job will run on
      runs-on: ubuntu-latest

      # Steps represent a sequence of tasks that will be executed as part of the job
      steps:
        # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
        - uses: actions/checkout@v2

        # Generates a BoM and uploads it to OWASP Dependency Track
        - name: Generates BoM and upload to OWASP DTrack
#          id: riskscoreFromDT
#          uses:  Quobis/action-owasp-dependecy-track-check@main
#          with:
#            url: "http://54.208.64.159:8080"
#            key: "721f36c18302e3ad420d8ff5de13561e9eae4be3"
#            language: "java"

          uses: DependencyTrack/gh-upload-sbom@v1.0.0
          with:
            serverhostname: "http://54.208.64.159:8080"
            apikey: "721f36c18302e3ad420d8ff5de13561e9eae4be3"
            projectname: "cartservice"
            projectversion: 'main'

        # Show the risk score output
#        - name: Get the output time
#          run: echo "The risk score of the project is ${{ steps.riskscoreFromDT.outputs.riskscore }}"